#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : xattr
Version  : 0.7.8
Release  : 13
URL      : https://pypi.python.org/packages/source/x/xattr/xattr-0.7.8.tar.gz
Source0  : https://pypi.python.org/packages/source/x/xattr/xattr-0.7.8.tar.gz
Summary  : Python wrapper for extended filesystem attributes
Group    : Development/Tools
License  : MIT
Requires: xattr-bin
Requires: xattr-python
BuildRequires : cffi
BuildRequires : cffi-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : pycparser
BuildRequires : pycparser-python
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
xattr is a Python wrapper for extended filesystem attributes.
Extended attributes extend the basic attributes of files and directories
in the file system.  They are stored as name:data pairs associated with
file system objects (files, directories, symlinks, etc).

%package bin
Summary: bin components for the xattr package.
Group: Binaries

%description bin
bin components for the xattr package.


%package python
Summary: python components for the xattr package.
Group: Default

%description python
python components for the xattr package.


%prep
%setup -q -n xattr-0.7.8

%build
python2 setup.py build -b py2
python3 setup.py build -b py3

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
python2 setup.py test || :
%install
rm -rf %{buildroot}
python2 setup.py build -b py2 install --root=%{buildroot}
python3 setup.py build -b py3 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/xattr

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
