#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : xattr
Version  : 0.9.1
Release  : 22
URL      : http://pypi.debian.net/xattr/xattr-0.9.1.tar.gz
Source0  : http://pypi.debian.net/xattr/xattr-0.9.1.tar.gz
Summary  : Python wrapper for extended filesystem attributes
Group    : Development/Tools
License  : MIT
Requires: xattr-bin
Requires: xattr-python
BuildRequires : cffi
BuildRequires : pbr
BuildRequires : pip
BuildRequires : pycparser
BuildRequires : pycparser-python
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
xattr
-----
.. image:: https://travis-ci.org/xattr/xattr.svg?branch=master
:target: https://travis-ci.org/xattr/xattr

%package bin
Summary: bin components for the xattr package.
Group: Binaries

%description bin
bin components for the xattr package.


%package python
Summary: python components for the xattr package.
Group: Default

%description python
python components for the xattr package.


%prep
%setup -q -n xattr-0.9.1

%build
export LANG=C
python2 setup.py build -b py2
python3 setup.py build -b py3

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
PYTHONPATH=%{buildroot}/usr/lib/python2.7/site-packages python2 setup.py test || :
%install
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot}
python3 -tt setup.py build -b py3 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/xattr

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
